// Generates migrations/0002_seed.sql and public/data/menu.json from data/menu.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { categories, items, branches, settings } from '../data/menu.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const q = (v) => (v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const now = Math.floor(Date.now() / 1000);

const cats = categories.map((c, i) => ({
  tagline_ar: '', tagline_en: '', allows_combo: 0, allows_addons: 0, active: 1, ...c, sort: (i + 1) * 10,
}));
const its = items.map((it, i) => ({
  desc_ar: '', desc_en: '', note_ar: '', note_en: '', image: '', tags: [], featured: 0, sold_out: 0,
  is_addon: 0, active: 1, ...it, sort: (i + 1) * 10, updated_at: now,
}));

const sql = ['-- Generated by scripts/build-seed.mjs — do not edit by hand', ''];
for (const c of cats) {
  sql.push(`INSERT OR REPLACE INTO categories (id,name_ar,name_en,tagline_ar,tagline_en,sort,allows_combo,allows_addons,active) VALUES (${[c.id, c.name_ar, c.name_en, c.tagline_ar, c.tagline_en, c.sort, c.allows_combo, c.allows_addons, c.active].map(q).join(',')});`);
}
for (const it of its) {
  sql.push(`INSERT OR REPLACE INTO items (id,category_id,name_ar,name_en,desc_ar,desc_en,note_ar,note_en,image,sizes,tags,featured,sold_out,is_addon,active,sort,updated_at) VALUES (${[it.id, it.category_id, it.name_ar, it.name_en, it.desc_ar, it.desc_en, it.note_ar, it.note_en, it.image, JSON.stringify(it.sizes), JSON.stringify(it.tags), it.featured, it.sold_out, it.is_addon, it.active, it.sort, it.updated_at].map(q).join(',')});`);
}
for (const b of branches) {
  sql.push(`INSERT OR REPLACE INTO branches (id,name_ar,name_en,address_ar,address_en,phone,whatsapp,maps_url,rating,reviews,open_time,close_time,delivery,accepting,sort) VALUES (${[b.id, b.name_ar, b.name_en, b.address_ar, b.address_en, b.phone, b.whatsapp, b.maps_url, b.rating, b.reviews, b.open_time, b.close_time, b.delivery, b.accepting, b.sort].map(q).join(',')});`);
}
for (const [k, v] of Object.entries(settings)) {
  sql.push(`INSERT OR IGNORE INTO settings (key,value) VALUES (${q(k)},${q(v)});`);
}
writeFileSync(join(root, 'migrations/0002_seed.sql'), sql.join('\n') + '\n');

// Static fallback in exactly the shape GET /api/menu returns
const menu = {
  version: now,
  categories: cats.filter((c) => c.active).map(({ active, ...c }) => c),
  items: its.filter((i) => i.active).map(({ active, updated_at, ...i }) => ({ ...i, unavailable: [] })),
  branches,
  settings,
};
writeFileSync(join(root, 'public/data/menu.json'), JSON.stringify(menu));
console.log(`seed: ${cats.length} categories, ${its.length} items, ${branches.length} branches`);
